config/routes.rb
Rails.application.routes.draw do
  root to: 'students#index'
  devise_for :students
  resources :dots, only: [:new, :create, :show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ActiveHash::Base
  self.data = [
    { id: 1, name: '日々の授業'}, { id: 2, name: '家庭学習'},
    { id: 3, name: '模試'}, { id: 4, name: '総合学習'},
    { id: 5, name: 'ボランティア活動'}, { id: 6, name: '検定等受検'},
    { id: 7, name: '部活動'}, { id: 8, name: '日常の気づき'},
    { id: 9, name: '趣味の中で'}, { id: 10, name: 'その他'}
  ]
  include ActiveHash::Associations
  has_many :dots
end

app/models/dot.rb
class Dot < ApplicationRecord
  belongs_to :student
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :category

  with_options presence: true do
    validates :title
    validates :category_id
    validates :introduction
    validates :effort
    validates :study
    validates :acted_at
  end
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  with_options presence: true do
    validates :name
    validates :grade
    validates :team
    validates :number
  end

  has_many :dots
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_student!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :configure_permitted_parameters_edit, if: :devise_controller?

  private
  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :grade, :team, :number])
  end

  def configure_permitted_parameters_edit
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :grade, :team, :number])
  end
end

app/controllers/dots_controller.rb
class DotsController < ApplicationController
  before_action :move_to_index, only: [:show, :edit, :update, :destroy]
  before_action :set_dot, only: [:show, :edit, :update]

  def new
    @dot = Dot.new
  end

  def create
    @dot = Dot.new(dot_params)
    if @dot.valid?
      @dot.save
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @dot.update(dot_params)
      redirect_to dot_path(@dot.id)
    else
      render :edit
    end
  end

  def destroy
    dot = Dot.find(params[:id])
    dot.destroy
    redirect_to root_path
  end

  private
  def dot_params
    params.require(:dot).permit(:title, :category_id, :introduction, :effort, :study, :acted_at).merge(student_id: current_student.id)
  end

  def set_dot
    @dot = Dot.find(params[:id])
  end

  def move_to_index
    dot = Dot.find(params[:id])
    unless dot.student_id == current_student.id
      redirect_to root_path
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :authenticate_student!, except: :index

  def index
    if student_signed_in?
      @dots = current_student.dots.order("acted_at DESC")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dots_helper.rb
module DotsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/dots/_form.html.erb
<%= form_with(model: dot, local: true) do |f| %>
  <%= render partial: 'layouts/error_messages', model: f.object %>

  <div class="form_parts">
    <%= f.label "タイトル" %>
    <%= f.text_field :title, placeholder: "タイトル" %>
  </div>

  <div class="form_parts">
    <%= f.label "活動日" %>
    <%= f.date_field :acted_at %>
  </div>

  <div class="form_parts">
    <%= f.label "カテゴリー" %>
    <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: "---"} %>
  </div>

  <div class="form_parts">
    <%= f.label "概要" %>
    <%= f.text_area :introduction, placeholder: "どんな活動をしたか記入" %>
  </div>

  <div class="form_parts">
    <%= f.label "頑張ったこと" %>
    <%= f.text_area :effort, placeholder: "自分なりに頑張ったことを記入" %>
  </div>

  <div class="form_parts">
    <%= f.label "活動を通して学んだこと" %>
    <%= f.text_area :study, placeholder: "活動を通して学んだことを記入" %>
  </div>

  <div class="dot_action">
    <%= f.submit "作成", class: "dot_action_btn" %>
  </div>

<% end %>

app/views/dots/edit.html.erb
<div class="contents_wrapper">
  <div class="contents">
    <div class="form_wrapper">
      <h1 class="dot_action_title">Edit Dot</h1>
      <%= render partial: 'form', locals: {dot: @dot} %>
    </div>
  </div>
</div>

app/views/dots/new.html.erb
<div class="contents_wrapper">
  <div class="contents">
    <div class="form_wrapper">
      <h1 class="dot_action_title">New Dot</h1>
      <%= render partial: 'form', locals: {dot: @dot} %>
    </div>
  </div>
</div>

app/views/dots/show.html.erb
<div class="contents_wrapper">
  <div class="contents">
    <div class="operation_buttons">
      <%= link_to '編集', edit_dot_path(@dot.id), class: "ope_btn" %>
      <%= link_to '削除', dot_path(@dot.id), method: :delete, class: "ope_btn" %>
    </div>
    <table class="dot_table">
      <tr>
        <th class="single_row_table">タイトル</th>
        <td class="single_row_table"><%= @dot.title %></td>
      </tr>

      <tr>
        <th class="single_row_table">活動日</th>
        <td class="single_row_table"><%= @dot.acted_at %></td>
      </tr>

      <tr>
        <th class="single_row_table">カテゴリー</th>
        <td class="single_row_table"><%= @dot.category.name %></td>
      </tr>
      <tr>
        <th class="single_row_table">活動概要</th>
        <td><%= @dot.introduction %></td>
      </tr>
      <tr>
        <th class="single_row_table">頑張ったこと</th>
        <td><%= @dot.effort %></td>
      </tr>

      <tr>
        <th class="single_row_table">学んだこと</th>
        <td><%= @dot.study %></td>
      </tr>

    </table>
  </div>
</div>

app/views/layouts/_error_messages.html.erb
<% if @dot.errors.any? %>
  <div class="error-alert">
    <ul>
      <% @dot.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConnectingDots</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header class="header">
      <div class="header_title_box">
        <%= link_to 'Connecting the Dots',root_path, class: "header_title" %>
        <p class="header_title_bottom">-for Students</p>
      </div>
      <div class="header_right">
        <% if student_signed_in? %>
          <ul class="header_buttons">
            <li class="new_dot">
              <%= link_to "New Dot", new_dot_path, class: "new_dot_btn" %>
            </li>
            <li class="student_session">
              <p id="menu_trigger">Student</p>
            </li>
          </ul>
          <ul id="session_menu">
            <li class="menu_list" id="student_edit"><%= link_to "生徒情報編集", edit_student_registration_path %></li>
            <li class="menu_list"><%= link_to "ログアウト", destroy_student_session_path, method: :delete, class: "session_btn" %></li>
          </ul>
        <% else %>
          <ul class="header_buttons">
            <li class="student_session">
              <%= link_to "ログイン", new_student_session_path, class: "session_btn" %>
            </li>
            <li class="student_session">
              <%= link_to "新規登録", new_student_registration_path, class: "session_btn" %>
            </li>
          </ul>
        <% end %>
      </div>
    </header>
    <div class="student_info">
      <% if student_signed_in? %>
        <p class="student_num"><%= current_student.grade %>年</p>
        <p class="student_num"><%= current_student.team %>組</p>
        <p class="student_num"><%= current_student.number %>番：</p>
        <p class="student_name"><%= current_student.name %></p>
      <% else %>
        右上のボタンから<b>「ログイン」</b>または<b>「新規登録」</b>してください
      <% end %>
    </div>
    <div class="wrapper">
      <%= yield %>
    </div>
    <footer class="footer">
      <p class="footer-content">Copyright Connecting the Dots -for Students 2021.</p>
    </footer>
  </body>
</html>

app/views/students/index.html.erb
<% if student_signed_in? %>
  <div class="contents_wrapper">
    <div class="contents">
      <% @dots.each do |dot| %>
        <div class="dot">
          <div class="dot_upper">
            <%= link_to dot.title, dot_path(dot.id) %>
          </div>
          <div class="dot_bottom">
            <div class="acted_at">
              <div class="act">
                活動日：
              </div>
              <div class="date">
                <%= dot.acted_at %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% else %>
  <div class="top-imagewrapper">
    <%= image_tag 'phonto.jpg', class: "top-image"%>
  </div>
  <div class="app-info">
    <div class="app-introduction">
      <h2 class="intro-title">＜自分と「対話」しよう＞</h2>
      <p class="app-exp">「自分って何がしたいんだっけ…？」</p>
      <p class="app-exp">他人の多様な生き方に触れられるこんな時代だからこそ、</p>
      <p class="app-exp">じっくり自分と「対話」することが求められる。</p>
      <p class="app-exp">自分との「対話」を通して、「理想の自分」と繋がろう。</p>
    </div>
    <div class="app-introduction">
      <h2 class="intro-title">＜使い方＞</h2>
      <p class="app-exp">日記のように、</p>
      <p class="app-exp">日常のあらゆるできごとの中で</p>
      <p class="app-exp">考えたこと・感じたことを「Dot」として記録していく。</p>
      <p class="app-exp">作成した「Dot」は一覧表示が可能。</p>
      <p class="app-exp">一覧表示された「Dot」を眺めて、</p>
      <p class="app-exp">自分の好きなことや得意なこと、自分が大切にしている価値観を見つけていこう。</p>
    </div>
  </div>
<% end %>